### ISSUE TITLE
(Question) Is posible to read Mifare cards via USB HID?

### ISSUE THREAD

**Issue by danicomas** [CardContact/scsh-scripts#1]
I have the following device https://www.elotouch.com/accessories/nfc-rfid.html and I would like to know if is posible to read Mifare cards via USB HID.

I have tried load('mifare/readmifare.js') but GPError: Card (CARD_CONNECT_FAILED/0) - "No card in reader or mute card."  is responding. However, if I use Manufacturer HEX program I can read the data.

@frankthater @CardContact

P.S: Official ELO device document https://docs.elotouch.com/accessories/accessories/_UIC680TG_Programmer_s_Manual_REV_2.7.pdf

**Comment by vessokolev** [comment]
I had the same problem on CentOS 8 and Rocky Linux 8. Running Smart Card Shell 3. Once trying to access CardContact HSD token, I used to get only:

>load("keymanager/keymanager.js");
GPError: Card (CARD_CONNECT_FAILED/0) - "No card in reader or mute card." in /home/vesso/CardContact/scsh3/keymanager/keymanager.js#2456
    at /home/vesso/CardContact/scsh3/keymanager/keymanager.js#2456

The token was neither locked or muted. I was able to use it in NSS (Mozilla, Brave). pcks11-tool was also able to access the card:

[vesso@localhost ~]$ pkcs11-tool -L
Available slots:
Slot 0 (0x0): Identiv uTrust 3512 SAM slot Token [CCID Interface] (55511822...
  token label        : SmartCard-HSM (UserPIN)
  token manufacturer : www.CardContact.de
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 24.13
  firmware version   : 3.5
  serial num         : DECC09000XX
  pin min/max        : 6/15

I tried that on several fresh installations to be sure I don't encounter some local problem.

Seems like it is a Java OpenJDK version problem. The only way to solve that problem is to upgrade your Java OpenJDK to as higher version is possible. Then set that version default by means of alternatives:

  Selection    Command
-----------------------------------------------
*+ 1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64/jre/bin/java)
   2           java-17-openjdk.x86_64 (/usr/lib/jvm/java-17-openjdk-17.0.1.0.12-2.el8_5.x86_64/bin/java)

Enter to keep the current selection[+], or type selection number: 2

After that, the HSM token can be read.

Note, that pair of problem and fix applies to Nitrokey HSM tokens too!
